baseURL = 'https://dylan-maclean.com'
languageCode = 'en-us'
title = 'Dylan Maclean'
author = 'Dylan Maclean'
theme = 'risotto'
DefaultContentLanguage = "en-us"

[params.about]
title = "Dylan Maclean"
description = "My personal blog and website about computers and cyber security."
logo = "🧑‍💻"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/DDMac224"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/dylan-maclean/"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:contact@dylan-maclean.com"

[menu]

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

[markup]

  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true
